### ISSUE TITLE
KMSI and Help links

### ISSUE THREAD

**Issue by JamesEdmonds89** [PhilipHaglund/PowerShell#2]
Sorry, Philip, not an issue but a question;

I see you have enabled keep me signed in. Did you set this by doing
`Set-AdfsProperties -EnableKmsi:$true` ?

Also, your help link on the footer, does it point to the same page that the "Need Help?" link points to?
If so, what URL do I need to specify to have them point to the same page?

Thanks

**Comment by PhilipHaglund** [comment]
Hi if you check the "Install-ADFSFarm.ps1" script you see all configuration settings for the actual ADFS role. I think it enabled Kmsi as you described.

The "Need Help?" link at the footer is a basic "Mailto:servicedesk@contoso.com" link.

**Comment by JamesEdmonds89** [comment]
Ah yes I see that now. Will do the same.

Ok cool, that's what I have mine set to, so will leave like that!

Thank you!
